# ########################## # 
#                            #
#    Skyauth Plugin YAML     #
#                            #
#   No configuration here !  #
#                            #
# ########################## #
#                            #
#  You can change 'default'  #
#      in 'permissions'      #
#    if you don't have a     #
#     permission plugin.     #
#                            #
# ########################## #

name: Skyauth
main: fr.skyost.auth.AuthPlugin
description: A lightweight auth plugin.
version: 0.7.2
author: Skyost
website: http://dev.bukkit.org/bukkit-plugins/skyauth/
commands:
 login:
  aliases: [log-in]
  description: Login on this server.
  usage: Use /login <password> to login on this server.
  permission: skyauth.login
 logout:
  aliases: [log-out]
  description: Logout from this server.
  usage: Use /logout to logout from this server.
  permission: skyauth.logout
 register:
  description: Register on this server.
  usage: Use /register <password> <confirm> to register on this server.
  permission: skyauth.register
 change:
  description: Change your password on this server.
  usage: Use /change <code> <password> <confirm> to change your password on this server.
  permission: skyauth.change
 reload-skyauth:
  aliases: [skyauth-reload]
  description: Reload the config / MySQL database.
  usage: Use /reload-skyauth to reload your configuration or your MySQL database.
  permission: skyauth.reload
permissions:
 skyauth.login:
  default: true
  description: Allow you to login on this server.
 skyauth.logout:
  default: true
  description: Allow you to logout from this server.
 skyauth.register:
  default: true
  description: Allow you to register on this server.
 skyauth.change:
  default: true
  description: Allow you to change your password on this server.
 reload-skyauth:
  default: op
  description: Allow you to reload the config / MySQL database.
 skyauth.bypass:
  default: false
  description: Allow you to bypass the auth system.